/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.ac.unikom.rpl.kelompok3.Main;


import id.ac.unikom.rpl.kelompok3.dao.PeminjamanDAO;
import id.ac.unikom.rpl.kelompok3.daoimpl.PeminjamanDAOImpl;
import id.ac.unikom.rpl.kelompok3.entity.Anggota;
import id.ac.unikom.rpl.kelompok3.entity.Buku;
import id.ac.unikom.rpl.kelompok3.entity.Peminjaman;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Nugraha
 */
public class FormPeminjaman extends javax.swing.JDialog {

    /**
     * Creates new form FormPeminjaman2
     */
    private Peminjaman peminjaman;
    private Anggota anggota;
    private Buku buku;
    private Calendar tglPinjam;
    
    public FormPeminjaman(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        datePeminjaman = new com.toedter.calendar.JDateChooser();
        labelIdAnggota = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        fieldIdAnggota = new javax.swing.JTextField();
        fieldIdBuku = new javax.swing.JTextField();
        buttonBatal = new javax.swing.JButton();
        buttonCariBuku = new javax.swing.JButton();
        fieldNamaAnggota = new javax.swing.JTextField();
        labelNamaAnggota = new javax.swing.JLabel();
        buttonCariAnggota = new javax.swing.JButton();
        fieldJudulBuku = new javax.swing.JTextField();
        labelTanggalPeminjaman = new javax.swing.JLabel();
        labelIdBuku = new javax.swing.JLabel();
        labelJudulBuku = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        datePeminjaman.setBackground(new java.awt.Color(255, 255, 255));

        labelIdAnggota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelIdAnggota.setText("ID");

        buttonSimpan.setBackground(new java.awt.Color(255, 255, 255));
        buttonSimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonSimpan.setText("Simpan");
        buttonSimpan.setBorder(null);
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        fieldIdAnggota.setEditable(false);
        fieldIdAnggota.setBackground(new java.awt.Color(255, 255, 255));
        fieldIdAnggota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fieldIdBuku.setEditable(false);
        fieldIdBuku.setBackground(new java.awt.Color(255, 255, 255));
        fieldIdBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonBatal.setBackground(new java.awt.Color(255, 255, 255));
        buttonBatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonBatal.setText("Batal");
        buttonBatal.setBorder(null);
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        buttonCariBuku.setBackground(new java.awt.Color(255, 255, 255));
        buttonCariBuku.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCariBuku.setText("....");
        buttonCariBuku.setBorder(null);
        buttonCariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariBukuActionPerformed(evt);
            }
        });

        fieldNamaAnggota.setEditable(false);
        fieldNamaAnggota.setBackground(new java.awt.Color(255, 255, 255));
        fieldNamaAnggota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelNamaAnggota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNamaAnggota.setText("Nama");

        buttonCariAnggota.setBackground(new java.awt.Color(255, 255, 255));
        buttonCariAnggota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonCariAnggota.setText("....");
        buttonCariAnggota.setBorder(null);
        buttonCariAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariAnggotaActionPerformed(evt);
            }
        });

        fieldJudulBuku.setEditable(false);
        fieldJudulBuku.setBackground(new java.awt.Color(255, 255, 255));
        fieldJudulBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelTanggalPeminjaman.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTanggalPeminjaman.setText("Tanggal Peminjaman");

        labelIdBuku.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelIdBuku.setText("ID");

        labelJudulBuku.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelJudulBuku.setText("Judul");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelIdAnggota)
                        .addGap(37, 37, 37)
                        .addComponent(fieldIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(buttonCariAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(labelIdBuku)
                        .addGap(37, 37, 37)
                        .addComponent(fieldIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNamaAnggota)
                        .addGap(18, 18, 18)
                        .addComponent(fieldNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(labelJudulBuku)
                        .addGap(18, 18, 18)
                        .addComponent(fieldJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelTanggalPeminjaman)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(datePeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldIdAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdAnggota)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(buttonCariAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdBuku)
                            .addComponent(buttonCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldNamaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNamaAnggota)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelJudulBuku))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(labelTanggalPeminjaman)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datePeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCariAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariAnggotaActionPerformed
        FormCariAnggota fca = new FormCariAnggota(null, true);
        fca.setLocationRelativeTo(null);
        fca.setVisible(true);

        anggota = fca.getAnggota();
        if (anggota != null) {
            fieldIdAnggota.setText(anggota.getIdAnggota());
            fieldNamaAnggota.setText(anggota.getNama());
        }
    }//GEN-LAST:event_buttonCariAnggotaActionPerformed

    private void buttonCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariBukuActionPerformed
        FormCariBuku fcb = new FormCariBuku(null, true);
        fcb.setLocationRelativeTo(null);
        fcb.setVisible(true);

        buku = fcb.getBuku();
        if (anggota != null) {
            fieldIdBuku.setText(buku.getIdBuku());
            fieldJudulBuku.setText(buku.getJudul());
        }
    }//GEN-LAST:event_buttonCariBukuActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        simpanPeminjaman();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        dispose();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void simpanPeminjaman() {
        
        // ambil tanggal peminjaman
        tglPinjam = datePeminjaman.getCalendar();
        
        // proses insert
        PeminjamanDAO dao = new PeminjamanDAOImpl();
        boolean sukses = dao.pinjam(Integer.parseInt(anggota.getIdAnggota()), 
                Integer.parseInt(buku.getIdBuku()), tglPinjam);
        if (sukses) {
            JOptionPane.showMessageDialog(this, "Peminjaman berhasil dilakukan ");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Peminjaman gagal dilakukan");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPeminjaman dialog = new FormPeminjaman(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonCariAnggota;
    private javax.swing.JButton buttonCariBuku;
    private javax.swing.JButton buttonSimpan;
    private com.toedter.calendar.JDateChooser datePeminjaman;
    private javax.swing.JTextField fieldIdAnggota;
    private javax.swing.JTextField fieldIdBuku;
    private javax.swing.JTextField fieldJudulBuku;
    private javax.swing.JTextField fieldNamaAnggota;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelIdAnggota;
    private javax.swing.JLabel labelIdBuku;
    private javax.swing.JLabel labelJudulBuku;
    private javax.swing.JLabel labelNamaAnggota;
    private javax.swing.JLabel labelTanggalPeminjaman;
    // End of variables declaration//GEN-END:variables
}
