/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package id.ac.unikom.rpl.kelompok3.Main;

import id.ac.unikom.rpl.kelompok3.dao.AdminDAO;
import id.ac.unikom.rpl.kelompok3.dao.AnggotaDAO;
import id.ac.unikom.rpl.kelompok3.dao.PegawaiDAO;
import id.ac.unikom.rpl.kelompok3.daoimpl.AdminDAOImpl;
import id.ac.unikom.rpl.kelompok3.daoimpl.AnggotaDAOImpl;
import id.ac.unikom.rpl.kelompok3.daoimpl.PegawaiDAOImpl;
import id.ac.unikom.rpl.kelompok3.entity.Anggota;
import id.ac.unikom.rpl.kelompok3.entity.Pegawai;
import javax.swing.JOptionPane;

/**
 *
 * @author Nugraha
 */
public class FormLogin extends javax.swing.JDialog {

    /**
     * Creates new form FormLogin
     */
    
    
    public FormLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldUsername = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        buttonMasuk = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(403, 370));
        getContentPane().setLayout(null);

        fieldUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fieldUsername.setForeground(new java.awt.Color(51, 51, 51));
        fieldUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldUsername.setBorder(null);
        fieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(fieldUsername);
        fieldUsername.setBounds(120, 100, 140, 50);

        fieldPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fieldPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldPassword.setBorder(null);
        fieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(fieldPassword);
        fieldPassword.setBounds(120, 160, 140, 40);

        buttonMasuk.setBackground(new java.awt.Color(51, 51, 51));
        buttonMasuk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonMasuk.setForeground(new java.awt.Color(255, 255, 255));
        buttonMasuk.setText("Login");
        buttonMasuk.setBorder(null);
        buttonMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMasukActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMasuk);
        buttonMasuk.setBounds(80, 240, 90, 40);

        buttonKeluar.setBackground(new java.awt.Color(51, 51, 51));
        buttonKeluar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonKeluar.setForeground(new java.awt.Color(255, 255, 255));
        buttonKeluar.setText("Exit");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKeluar);
        buttonKeluar.setBounds(220, 240, 90, 40);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 0);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setText("APLIKASI S.I PERPUSTAKAAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 360, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
       dispose();
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void buttonMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMasukActionPerformed

        String username = fieldUsername.getText();
        String password = String.valueOf(fieldPassword.getPassword());
        

        AdminDAO dao = new AdminDAOImpl();
        Pegawai pegawai = dao.login(username, password);
        
        
        // cek hasil login
        if (pegawai != null) {
            JOptionPane.showMessageDialog(this, 
                    "Login berhasil : " + pegawai.getNama());
            FormUtama fu = new FormUtama();
            fu.setLocationRelativeTo(null);
            fu.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, 
                    "Login gagal");
        }
               
    }//GEN-LAST:event_buttonMasukActionPerformed

    private void fieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasswordActionPerformed

    private void fieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormLogin dialog = new FormLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonMasuk;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
